[package]
name = "system"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
tempfile = "3.10.1"
reqwest = { version = "0.12.5", features = ["blocking"] }
sha2 = "0.10.8"
clap = { version = "4.5.9", features = ["derive"] }
